---
# Source: flux2/templates/notification-controller-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: "flux-system"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "0.37.0"
    app.kubernetes.io/part-of: flux
    helm.sh/chart: flux2-2.5.1
  name: notification-controller
---
# Source: flux2/templates/notification-controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: "flux-system"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "0.37.0"
    app.kubernetes.io/part-of: flux
    helm.sh/chart: flux2-2.5.1
    control-plane: controller
  name: notification-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: notification-controller
  type: ClusterIP
---
# Source: flux2/templates/notification-controller-webhook-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: "flux-system"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "0.37.0"
    app.kubernetes.io/part-of: flux
    helm.sh/chart: flux2-2.5.1
    control-plane: controller
  name: webhook-receiver
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9292
  selector:
    app: notification-controller
  type: ClusterIP
---
# Source: flux2/templates/notification-controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: "flux-system"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "0.37.0"
    app.kubernetes.io/part-of: flux
    helm.sh/chart: flux2-2.5.1
    control-plane: controller
  name: notification-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-controller
  template:
    metadata:
      annotations: 
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: notification-controller

    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --watch-all-namespaces=true
        - --log-level=info
        - --log-encoding=json
        - --enable-leader-election
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/fluxcd/notification-controller:v0.29.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 9292
          name: http-webhook
          protocol: TCP
        - containerPort: 8080
          name: http-prom
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources: 
          limits: {}
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp
          name: temp
      serviceAccountName: notification-controller
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: temp
